name: musker-app
services:
  - name: web
    image:
      # This will be replaced by the helper script with an image like "username/musker:tag"
      repository: "__IMAGE__"
    run_command: "gunicorn social.wsgi:application --bind 0.0.0.0:$PORT"
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: DJANGO_SECRET_KEY
        scope: RUN_TIME
        value: ""
      - key: DJANGO_DEBUG
        scope: RUN_TIME
        value: "False"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ""
      - key: ALLOWED_HOSTS
        scope: RUN_TIME
        value: ""
      - key: EMAIL_HOST_PASSWORD
        scope: RUN_TIME
        value: ""
      - key: STRIPE_PUBLIC_KEY
        scope: RUN_TIME
        value: ""
      - key: STRIPE_SECRET_KEY
        scope: RUN_TIME
        value: ""
      - key: STRIPE_WEBHOOK_SECRET
        scope: RUN_TIME
        value: ""
